version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-translation
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # 如果有 NVIDIA GPU，取消下面的註釋
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  translation-service:
    build: ./translation-service
    container_name: translation-api
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - NODE_ENV=production
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data: